apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backendapp
  template:
    metadata:
      labels:
        app: backendapp
    spec:
      containers:
        - name: backendapp
          image: filiprak2000/nodejsapp:v3 
          volumeMounts: 
            - mountPath: /app/savedFiles
              name: myvolumexd
      volumes:
        - name: myvolumexd
          hostPath: 
            path: /data1
            type: DirectoryOrCreate
