apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  volumeName: my-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  
  resources:
    requests:
      storage: 1Gi